config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :answers, only: [:destroy]

  resources :questions do
    resource :answers, shallow: true
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :body, :question_id, :user_id, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, :body, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :confirmable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def owner_of?(model)
    model.user_id == id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:destroy]
  before_action :only_owner, only: [:destroy]

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = @question
    @answer.save
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question, notice: I18n.t('notices.answers.removed')
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

  def only_owner
    redirect_to @answer.question, alert: I18n.t('alerts.access_denied') unless current_user.owner_of?(@answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :only_owner, only: [:edit, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: I18n.t('notices.questions.created')
    else
      render 'new'
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: I18n.t('notices.questions.updated')
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: I18n.t('notices.questions.removed')
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def only_owner
    redirect_to @question, alert: I18n.t('alerts.access_denied') unless current_user.owner_of?(@question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.slim
li
  p= answer.body
  - if user_signed_in? && current_user.owner_of?(answer)
    = link_to t('questions.show.remove_answer'), answer, method: :delete, data: { confirm: t('common.sure') }

app/views/answers/create.js.erb
$('.answers').append('<%= j render @answer %>');
$('#answer_body').val('');

app/views/common/_errors.html.slim
- if resource.errors.any?
  div class="text-danger"
    h2
      = t('common.errors')

    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/layouts/application.html.slim
doctype html
html
  head
    title Qna
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - if user_signed_in?
      = link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      = link_to 'Sign in', new_user_session_path

    p class="notice"
      = notice

    p class="alert"
      = alert

    = yield

app/views/questions/_form.html.slim
= render 'common/errors', resource: @question

= form_for @question do |f|

  = f.label :title
  = f.text_field :title

  = f.label :body
  = f.text_area :body

  = f.submit

app/views/questions/edit.html.slim
= render 'form'

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path

ul
  - @questions.each do |question|
    li
      = link_to question.title, question

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
h1= @question.title

p= @question.body
- if user_signed_in? && current_user.owner_of?(@question)
  p= link_to t('questions.show.remove_question'), @question, method: :delete, data: { confirm: t('common.sure') }

p= link_to t('questions.show.write_answer'), new_question_answers_path(@question)

ul.answers
  = render @question.answers

- if user_signed_in?
  = form_for [@question, @answer], remote: true do |f|
    = f.label :body, 'Your answer'
    = f.text_area :body
    = f.submit 'Create Answer'
- else
  p= t('questions.show.need_sign_in')